name: macOS Build

on:
  # Läuft beim Pushen in einen der folgenden Zweige
  push:
    branches:
      - main

  # Wird bei Pull Request-Ereignissen ausgeführt, die auf einen der folgenden Zweige abzielen
  pull_request:
    branches:
      - main

  # Ermöglicht Ihnen, diesen Workflow manuell über die Registerkarte Aktionen des Repositorys auszuführen
  workflow_dispatch:

env:
  # https://flet.dev/docs/publish#versioning
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0

  # Zu verwendende Python-Version
  PYTHON_VERSION: 3.13.4

  # Für „flet build“ zu installierende flet-cli-Version
  FLET_CLI_VERSION: 0.27.5

  # Stellt sicher, dass Python standardmäßig die UTF-8-Kodierung verwendet
  PYTHONUTF8: 1

  # Deaktivieren Sie die Rich-Text-Formatierung in der Flet-CLI-Ausgabe
  FLET_CLI_NO_RICH_OUTPUT: 1

  # Deaktiviert Fortschrittsbalken bei der Verwendung von UV
  UV_NO_PROGRESS: 1

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install flet-cli ${{ env.FLET_CLI_VERSION }}
      run: |
        python -m pip install --upgrade pip
        pip install flet-cli==$FLET_CLI_VERSION

    - name: Flet Build macOS
      run: |
        flet build macos --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4.6.2  # https://github.com/marketplace/actions/upload-a-build-artifact
      with:
        name: macos-build-artifact  # the name of the artifact
        path: build/macos  # Speicherort der Flet-Build-Ausgabe
        if-no-files-found: error  # Wenn keine Dateien gefunden werden, wird die Aktion mit einer Fehlermeldung abgebrochen.
        overwrite: false  # Wenn „true“, wird ein Artefakt mit einem übereinstimmenden Namen gelöscht, bevor ein neues hochgeladen wird.
        # Wenn „false“, schlägt die Aktion fehl, wenn bereits ein Artefakt für den angegebenen Namen vorhanden ist.
        # Schlägt nicht fehl, wenn das Artefakt nicht vorhanden ist.
